name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Check login
        run: aws sts get-caller-identity
      - name: Check bucket reachability
        run: aws s3 ls "s3://${{ vars.S3_BUCKET }}"
      - name: Check Upload (Dry-Run)
        run: aws s3 sync ./dist "s3://${{ vars.S3_BUCKET }}" --delete --dryrun
      - name: Upload to S3
        run: aws s3 sync ./dist "s3://${{ vars.S3_BUCKET }}" --delete
      - name: List S3 Bucket
        run: aws s3 ls "s3://${{ vars.S3_BUCKET }}"
      - name: Temporary link
        run: aws s3 presign "s3://${{ vars.S3_BUCKET }}/index.html" --expires-in 300
